# Generated by Django 2.0.1 on 2018-01-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name_plural': 'insurance'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name_plural': 'laboratories'},
        ),
        migrations.AlterModelOptions(
            name='labresultupdated',
            options={'verbose_name_plural': 'lab results updated'},
        ),
    ]
