# Generated by Django 2.0.1 on 2018-01-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20180127_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Laboratory'),
        ),
    ]
